// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName
import { application } from "./application"
import CodeController from "./code_controller"
import EditorController from "./editor_controller"
import HelloController from "./hello_controller"


application.register("code", CodeController)
application.register("editor", EditorController)
application.register("hello", HelloController)
