// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CodeController from "./code_controller"
application.register("code", CodeController)

import EditorController from "./editor_controller"
application.register("editor", EditorController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ToggleMenuController from "./toggle_menu_controller"
application.register("toggle-menu", ToggleMenuController)
